//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace LoodonDAL.com.krayknot.wcfservices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServiceInsert", Namespace="http://tempuri.org/")]
    public partial class ServiceInsert : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddUserforLoodonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceInsert() {
            this.Url = global::LoodonDAL.Properties.Settings.Default.LoodonDAL_com_krayknot_wcfservices_ServiceInsert;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddUserforLoodonCompletedEventHandler AddUserforLoodonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceInsert/AddUserforLoodon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddUserforLoodon([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserDetails userDetails) {
            this.Invoke("AddUserforLoodon", new object[] {
                        userDetails});
        }
        
        /// <remarks/>
        public void AddUserforLoodonAsync(UserDetails userDetails) {
            this.AddUserforLoodonAsync(userDetails, null);
        }
        
        /// <remarks/>
        public void AddUserforLoodonAsync(UserDetails userDetails, object userState) {
            if ((this.AddUserforLoodonOperationCompleted == null)) {
                this.AddUserforLoodonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserforLoodonOperationCompleted);
            }
            this.InvokeAsync("AddUserforLoodon", new object[] {
                        userDetails}, this.AddUserforLoodonOperationCompleted, userState);
        }
        
        private void OnAddUserforLoodonOperationCompleted(object arg) {
            if ((this.AddUserforLoodonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserforLoodonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary_Krayknot")]
    public partial class UserDetails {
        
        private string users_AboutField;
        
        private string users_ActiveField;
        
        private string users_CompanyField;
        
        private string users_DateCreatedField;
        
        private string users_DomainField;
        
        private string users_EmailField;
        
        private string users_FullNameField;
        
        private string users_ImagePathField;
        
        private string users_IsAdminField;
        
        private string users_PasswordField;
        
        private string users_SoftwareField;
        
        private string users_UsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_About {
            get {
                return this.users_AboutField;
            }
            set {
                this.users_AboutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Active {
            get {
                return this.users_ActiveField;
            }
            set {
                this.users_ActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Company {
            get {
                return this.users_CompanyField;
            }
            set {
                this.users_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_DateCreated {
            get {
                return this.users_DateCreatedField;
            }
            set {
                this.users_DateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Domain {
            get {
                return this.users_DomainField;
            }
            set {
                this.users_DomainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Email {
            get {
                return this.users_EmailField;
            }
            set {
                this.users_EmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_FullName {
            get {
                return this.users_FullNameField;
            }
            set {
                this.users_FullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_ImagePath {
            get {
                return this.users_ImagePathField;
            }
            set {
                this.users_ImagePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_IsAdmin {
            get {
                return this.users_IsAdminField;
            }
            set {
                this.users_IsAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Password {
            get {
                return this.users_PasswordField;
            }
            set {
                this.users_PasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Software {
            get {
                return this.users_SoftwareField;
            }
            set {
                this.users_SoftwareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Users_Username {
            get {
                return this.users_UsernameField;
            }
            set {
                this.users_UsernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddUserforLoodonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591